### ISSUE TITLE
not connecting/reconnecting issues

### ISSUE THREAD

**Issue by tzapu** [vshymanskyy/blynk-library-js#2]
hi
when i m using a wrong token i get into a re-connection loop stating that connection is authorized. Is there an event that we could use for when it fails and disable the loop maybe, or handle it in a more straightforward manner?
Cheers

```
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
...
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
Connecting to SSL: cloud.blynk.cc 8441

**Comment by vshymanskyy** [comment]
Authorized actually means SSL authorization.
We can fix it so that the script closes if Auth Token check fails.. Would it be ok?

**Comment by tzapu** [comment]
yup, anything that would give me control over the retry connection or status of it would be perfect.
cheers

**Comment by tzapu** [comment]
added a pull request to fix this
https://github.com/vshymanskyy/blynk-library-js/pull/8

**Comment by vshymanskyy** [comment]
Merged.

**Comment by vshymanskyy** [comment]
pushed to npm
