### ISSUE TITLE
Fix to avoid disconnects when writing while not ready

### ISSUE THREAD

**Issue by BLavery** [vshymanskyy/blynk-library-js#32]
Under certain scenarios I get repeating connect/disconnect sequence. I get the same on Mint and on Raspberry Pi. Blynk-library downloaded by npm in last week.

Example guaranteed crash code:

`
#!/usr/bin/env nodejs
var token = 'a82b38d etc - use your own!   ';
var Blynk = require("blynk-library");
var blynk = new Blynk.Blynk(token);  // ssl default

//  Blinking LED widget at APP screen.
var V15 = new blynk.VirtualPin(15);
var ledval = 0;  // brightness
setInterval(function(){ 
  // we put a LED widget on phone APP at V15.   Let's  blink it on phone. 
  ledval = 255-ledval;
  V15.write(ledval);  
}, 200);   // 5/sec ie rather fast - first write is before conn is settled.

`
It seems if a virtual write is pushed out while socket connection is not stable, then the blynk process in nodejs immediately disconnects from the server. If the writes keep coming, the server is repeatedly disconnected, in a useless loop.

My solution is to change this line in blynk.js:
532      this.sendRsp(msg_type, msg_id, data.length, data);
into:
if ((typeof this.timerHb) === 'object' && this.timerHb != null) {this.sendRsp(msg_type, msg_id, data.length, data)};

Now, writes attempted during socket connection unavailability are simply dumped.
(timerHb is heartbeat/ping callback, and it seems to make a workable "flag" for indicating when conn is fully up.)

Brian

**Comment by vshymanskyy** [comment]
Thanks!
