### ISSUE TITLE
OnOff GPIO read error for Raspberry Pi.

### ISSUE THREAD

**Issue by BLavery** [vshymanskyy/blynk-library-js#33]
The inbuilt code to read GPIO at Raspberry Pi (using OnOff library) seems broken. The write/gpio output is OK, but read/gpio crashes.  (Blynk-library version = as fetched by npm in last week.)

My fix:
in file blynk-node.js, function BoardOnOff,  case "dr",  alter the line reading 
373        self.blynk.sendMsg(MsgType.HW, null, ['dw', values[1], value]);
to remove the parameter null, ie
    self.blynk.sendMsg(MsgType.HW, ['dw', values[1], value]);

Now it works fine.

Of course, the blynk/OnOff combination has no support for internal pullup resistors, so I have now gotten used to using rpio library to service my gpio button pins (withblynk  virtual pins), and leaving the inbuilt OnOff reads for plain vanilla gpio inputs.

Brian

**Comment by vshymanskyy** [comment]
Hi. Nice catch! Fix is on the way.
