### ISSUE TITLE
failed intial connection handling

### ISSUE THREAD

**Issue by tzapu** [vshymanskyy/blynk-library-js#5]
HI, it seems the lib throws and exception if for instance the port is wrong

12 Oct 18:26:02 - Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:959:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

expected behavior would be to fail gracefully with an event

cheers

**Comment by tzapu** [comment]
https://github.com/vshymanskyy/blynk-library-js/pull/8

**Comment by vshymanskyy** [comment]
Merged

**Comment by vshymanskyy** [comment]
pushed to npm
