### ISSUE TITLE
Get Blynk-library-js working on Espruino running natively on ESP8266

### ISSUE THREAD

**Issue by nkolban** [vshymanskyy/blynk-library-js#6]
There has been a project on the go for a couple of months which is a port of Espruino to native ESP8266 execution and it is progressing well to the point that there are now stable drivers.  This issue asks to see if there is interest in testing and collaboration on getting blynk-library-js running directly on Espruino running natively on ESP8266?

If yes, and the developers of the Espruino port to ESP8266 can assist, please contact kolban1@kolban.com or respond to this issue.

**Comment by vshymanskyy** [comment]
I am interested, but can't find a prebuilt firmware image for Espruino on ESP8266. It would make bring-up much easier.

**Comment by nkolban** [comment]
See the following ... https://github.com/espruino/EspruinoBuilds/tree/master/ESP8266

I am one of the contributors to this project and will be delighted to assist you with any knowledge or questions or comments you may have.  I can be found at kolban1@kolban.com or in the gitter chat room here ... https://gitter.im/espruino/Espruino

**Comment by vshymanskyy** [comment]
Thank you. I will check it soon!

**Comment by vshymanskyy** [comment]
I was able to flash and run the library, but I'm getting "ERROR: Out of Memory!" message.
I tried minifying and removing some stuff but no luck yet.

**Comment by nkolban** [comment]
I'll be delighted to assist as you need ... I can be pinged live at the Espruino gitter stream ... see:
https://gitter.im/espruino/Espruino

**Comment by vshymanskyy** [comment]
It looks like now we have more RAM accessible for JS on ESP8266.
Still not enough to run full Blynk library on it :(
It would be great if someone can help optimizing RAM usage of the library...

**Comment by vshymanskyy** [comment]
Looks much closer now!
I think the last issue that has to be resolved toward Blynk JS running on ESP8266:
http://forum.espruino.com/conversations/279159/

**Comment by rahul-thakoor** [comment]
Hello! This is exactly what i want to use. Is it possible yet? Or can be load blynk library from sd card?

**Comment by vshymanskyy** [comment]
Didn't try loading from SD... maybe it will work...

**Comment by rahul-thakoor** [comment]
Nice. Maybe a newbie question, but which filw to use? Espruino.js sufficient or is there a minified version? I mean i just use require espruino.js? Or how to install the library?

**Comment by vshymanskyy** [comment]
I'm giving up on this - I think it will run well on Esp32! ;)

**Comment by nkolban** [comment]
We now have a build of Espruino on ESP32.  Lots more resources.  Let me know if I can assist.
